const USAGE = "usage: deno run -A scripts/build_npm.ts <version>";

interface BuildContext {
  readonly projectRoot: string;
  readonly npmRoot: string;
  readonly version: string;
}

function parseArgs(argv: string[]): string {
  if (argv.length !== 1 || argv[0] === "-h" || argv[0] === "--help") {
    if (argv.length === 1 && (argv[0] === "-h" || argv[0] === "--help")) {
      console.log(USAGE);
      Deno.exit(0);
    }
    throw new Error(`${USAGE}\nmissing required argument: <version>`);
  }

  const version = argv[0].trim();
  if (!/^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/.test(version)) {
    throw new Error(`invalid version format: ${version}`);
  }
  return version;
}

function ensureCleanDir(path: string): void {
  try {
    Deno.removeSync(path, { recursive: true });
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) {
      throw error;
    }
  }
  Deno.mkdirSync(path, { recursive: true });
}

function copyDirectoryRecursive(sourceRoot: string, targetRoot: string): void {
  Deno.mkdirSync(targetRoot, { recursive: true });
  for (const entry of Deno.readDirSync(sourceRoot)) {
    const sourcePath = `${sourceRoot}/${entry.name}`;
    const targetPath = `${targetRoot}/${entry.name}`;
    if (entry.isDirectory) {
      copyDirectoryRecursive(sourcePath, targetPath);
      continue;
    }
    if (entry.isFile) {
      Deno.copyFileSync(sourcePath, targetPath);
    }
  }
}

function writePackageJson(context: BuildContext): void {
  const packageJson = {
    name: "agent-dock",
    version: context.version,
    private: true,
    description: "TypeScript runtime package for the agent-dock CLI",
    bin: {
      "agent-dock": "./bin/agent-dock",
    },
    files: [
      "bin",
      "src",
      "team_orchestrator",
      "codex_wrapper.sh",
      "README.md",
    ],
    engines: {
      node: ">=18",
    },
  };
  const output = `${JSON.stringify(packageJson, null, 2)}\n`;
  Deno.writeTextFileSync(`${context.npmRoot}/package.json`, output);
}

function writeNpmReadme(context: BuildContext): void {
  const content = [
    "# agent-dock (local build)",
    "",
    "This directory is generated by `scripts/build_npm.ts`.",
    "",
    "Regenerate:",
    "```bash",
    "deno run -A scripts/build_npm.ts 0.0.0-dev",
    "```",
    "",
    "Version:",
    `- ${context.version}`,
    "",
    "Usage:",
    "```bash",
    "./node_modules/.bin/agent-dock",
    "```",
    "",
  ].join("\n");
  Deno.writeTextFileSync(`${context.npmRoot}/README.md`, content);
}

function writeBinScript(context: BuildContext): void {
  const binDir = `${context.npmRoot}/bin`;
  Deno.mkdirSync(binDir, { recursive: true });

  const script = [
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "",
    'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
    'exec deno run -A "$SCRIPT_DIR/../src/cli/main.ts" "$@"',
    "",
  ].join("\n");
  const path = `${binDir}/agent-dock`;
  Deno.writeTextFileSync(path, script);
  Deno.chmodSync(path, 0o755);
}

function buildNpmArtifacts(context: BuildContext): void {
  ensureCleanDir(context.npmRoot);

  writePackageJson(context);
  writeNpmReadme(context);
  writeBinScript(context);

  copyDirectoryRecursive(
    `${context.projectRoot}/src`,
    `${context.npmRoot}/src`,
  );
  copyDirectoryRecursive(
    `${context.projectRoot}/team_orchestrator/personas/default`,
    `${context.npmRoot}/team_orchestrator/personas/default`,
  );
  Deno.copyFileSync(
    `${context.projectRoot}/codex_wrapper.sh`,
    `${context.npmRoot}/codex_wrapper.sh`,
  );
}

function main(): void {
  const version = parseArgs(Deno.args);
  const context: BuildContext = {
    projectRoot: Deno.cwd(),
    npmRoot: `${Deno.cwd()}/npm`,
    version,
  };

  buildNpmArtifacts(context);
  console.log(`npm artifacts generated at ${context.npmRoot}`);
}

if (import.meta.main) {
  try {
    main();
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) {
      console.error(
        `build failed: required path does not exist (${error.message})`,
      );
      Deno.exit(1);
    }
    if (error instanceof Error) {
      console.error(`build failed: ${error.message}`);
      Deno.exit(1);
    }
    console.error(`build failed: ${String(error)}`);
    Deno.exit(1);
  }
}
